name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+.*
  pull_request:
    branches:
      - '*'

jobs:
  push_to_registry:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: maxhollmann/envlinks
          tags: |
            type=ref,event=branch
            type=semver,pattern=v{{version}},event=tag
            type=semver,pattern=v{{major}},event=tag
            type=semver,pattern=v{{major}}.{{minor}},event=tag
            type=ref,event=pr
